# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/ExecutionEngine
    contrib/libs/llvm22/lib/ExecutionEngine/RuntimeDyld
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
    contrib/restricted/libffi
)

ADDINCL(
    contrib/libs/llvm22/lib/ExecutionEngine/Interpreter
    contrib/restricted/libffi/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Execution.cpp
    ExternalFunctions.cpp
    Interpreter.cpp
)

END()
