# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/ExecutionEngine/RuntimeDyld
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    JITSymbol.cpp
    RTDyldMemoryManager.cpp
    RuntimeDyld.cpp
    RuntimeDyldCOFF.cpp
    RuntimeDyldChecker.cpp
    RuntimeDyldELF.cpp
    RuntimeDyldMachO.cpp
    Targets/RuntimeDyldELFMips.cpp
)

END()
