# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/MC
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    ConstantPools.cpp
    DXContainerPSVInfo.cpp
    DXContainerRootSignature.cpp
    ELFObjectWriter.cpp
    GOFFObjectWriter.cpp
    MCAsmBackend.cpp
    MCAsmInfo.cpp
    MCAsmInfoCOFF.cpp
    MCAsmInfoDarwin.cpp
    MCAsmInfoELF.cpp
    MCAsmInfoGOFF.cpp
    MCAsmInfoWasm.cpp
    MCAsmInfoXCOFF.cpp
    MCAsmMacro.cpp
    MCAsmStreamer.cpp
    MCAssembler.cpp
    MCCodeEmitter.cpp
    MCCodeView.cpp
    MCContext.cpp
    MCDXContainerStreamer.cpp
    MCDXContainerWriter.cpp
    MCDwarf.cpp
    MCELFObjectTargetWriter.cpp
    MCELFStreamer.cpp
    MCExpr.cpp
    MCFragment.cpp
    MCGOFFStreamer.cpp
    MCInst.cpp
    MCInstPrinter.cpp
    MCInstrAnalysis.cpp
    MCInstrDesc.cpp
    MCInstrInfo.cpp
    MCLabel.cpp
    MCLinkerOptimizationHint.cpp
    MCMachOStreamer.cpp
    MCMachObjectTargetWriter.cpp
    MCNullStreamer.cpp
    MCObjectFileInfo.cpp
    MCObjectStreamer.cpp
    MCObjectWriter.cpp
    MCPseudoProbe.cpp
    MCRegisterInfo.cpp
    MCSFrame.cpp
    MCSPIRVStreamer.cpp
    MCSchedule.cpp
    MCSection.cpp
    MCSectionMachO.cpp
    MCStreamer.cpp
    MCSubtargetInfo.cpp
    MCSymbol.cpp
    MCSymbolELF.cpp
    MCSymbolGOFF.cpp
    MCSymbolXCOFF.cpp
    MCTargetOptions.cpp
    MCTargetOptionsCommandFlags.cpp
    MCValue.cpp
    MCWasmObjectTargetWriter.cpp
    MCWasmStreamer.cpp
    MCWin64EH.cpp
    MCWinCOFFStreamer.cpp
    MCWinEH.cpp
    MCXCOFFObjectTargetWriter.cpp
    MCXCOFFStreamer.cpp
    MachObjectWriter.cpp
    SPIRVObjectWriter.cpp
    StringTableBuilder.cpp
    TargetRegistry.cpp
    WasmObjectWriter.cpp
    WinCOFFObjectWriter.cpp
    XCOFFObjectWriter.cpp
)

END()
