# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Bitstream/Reader
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/DebugInfo/Symbolize
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/ProfileData
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DataAccessProf.cpp
    GCOV.cpp
    IndexedMemProfData.cpp
    InstrProf.cpp
    InstrProfCorrelator.cpp
    InstrProfReader.cpp
    InstrProfWriter.cpp
    ItaniumManglingCanonicalizer.cpp
    MemProf.cpp
    MemProfCommon.cpp
    MemProfRadixTree.cpp
    MemProfReader.cpp
    MemProfSummary.cpp
    MemProfSummaryBuilder.cpp
    PGOCtxProfReader.cpp
    PGOCtxProfWriter.cpp
    ProfileSummaryBuilder.cpp
    SampleProf.cpp
    SampleProfReader.cpp
    SampleProfWriter.cpp
    SymbolRemappingReader.cpp
)

END()
