# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/AsmParser
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/IRReader
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    IRReader.cpp
)

END()
