# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/BinaryFormat
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AMDGPUMetadataVerifier.cpp
    COFF.cpp
    DXContainer.cpp
    Dwarf.cpp
    ELF.cpp
    MachO.cpp
    Magic.cpp
    MsgPackDocument.cpp
    MsgPackDocumentYAML.cpp
    MsgPackReader.cpp
    MsgPackWriter.cpp
    SFrame.cpp
    Wasm.cpp
    XCOFF.cpp
)

END()
