# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/SandboxIR
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/Transforms/Vectorize
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    LoadStoreVectorizer.cpp
    LoopIdiomVectorize.cpp
    LoopVectorizationLegality.cpp
    LoopVectorize.cpp
    SLPVectorizer.cpp
    SandboxVectorizer/DependencyGraph.cpp
    SandboxVectorizer/InstrMaps.cpp
    SandboxVectorizer/Interval.cpp
    SandboxVectorizer/Legality.cpp
    SandboxVectorizer/Passes/BottomUpVec.cpp
    SandboxVectorizer/Passes/PackReuse.cpp
    SandboxVectorizer/Passes/RegionsFromBBs.cpp
    SandboxVectorizer/Passes/RegionsFromMetadata.cpp
    SandboxVectorizer/Passes/SeedCollection.cpp
    SandboxVectorizer/Passes/TransactionAcceptOrRevert.cpp
    SandboxVectorizer/Passes/TransactionSave.cpp
    SandboxVectorizer/SandboxVectorizer.cpp
    SandboxVectorizer/SandboxVectorizerPassBuilder.cpp
    SandboxVectorizer/Scheduler.cpp
    SandboxVectorizer/SeedCollector.cpp
    SandboxVectorizer/VecUtils.cpp
    VPlan.cpp
    VPlanAnalysis.cpp
    VPlanConstruction.cpp
    VPlanPredicator.cpp
    VPlanRecipes.cpp
    VPlanSLP.cpp
    VPlanTransforms.cpp
    VPlanUnroll.cpp
    VPlanUtils.cpp
    VPlanVerifier.cpp
    VectorCombine.cpp
    Vectorize.cpp
)

END()
