# Generated by devtools/yamaker.

PROGRAM()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/AsmParser
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/Bitstream/Reader
    contrib/libs/llvm22/lib/CGData
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGen/AsmPrinter
    contrib/libs/llvm22/lib/CodeGen/GlobalISel
    contrib/libs/llvm22/lib/CodeGen/SelectionDAG
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/DebugInfo/BTF
    contrib/libs/llvm22/lib/DebugInfo/CodeView
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/DebugInfo/GSYM
    contrib/libs/llvm22/lib/DebugInfo/MSF
    contrib/libs/llvm22/lib/DebugInfo/PDB
    contrib/libs/llvm22/lib/DebugInfo/Symbolize
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/Extensions
    contrib/libs/llvm22/lib/Frontend/Atomic
    contrib/libs/llvm22/lib/Frontend/HLSL
    contrib/libs/llvm22/lib/Frontend/Offloading
    contrib/libs/llvm22/lib/Frontend/OpenMP
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRPrinter
    contrib/libs/llvm22/lib/IRReader
    contrib/libs/llvm22/lib/Linker
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCDisassembler
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/ObjectYAML
    contrib/libs/llvm22/lib/Passes
    contrib/libs/llvm22/lib/Plugins
    contrib/libs/llvm22/lib/ProfileData
    contrib/libs/llvm22/lib/Remarks
    contrib/libs/llvm22/lib/SandboxIR
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/Target/AArch64
    contrib/libs/llvm22/lib/Target/AArch64/AsmParser
    contrib/libs/llvm22/lib/Target/AArch64/MCTargetDesc
    contrib/libs/llvm22/lib/Target/AArch64/TargetInfo
    contrib/libs/llvm22/lib/Target/AArch64/Utils
    contrib/libs/llvm22/lib/Target/ARM
    contrib/libs/llvm22/lib/Target/ARM/AsmParser
    contrib/libs/llvm22/lib/Target/ARM/MCTargetDesc
    contrib/libs/llvm22/lib/Target/ARM/TargetInfo
    contrib/libs/llvm22/lib/Target/ARM/Utils
    contrib/libs/llvm22/lib/Target/BPF
    contrib/libs/llvm22/lib/Target/BPF/AsmParser
    contrib/libs/llvm22/lib/Target/BPF/MCTargetDesc
    contrib/libs/llvm22/lib/Target/BPF/TargetInfo
    contrib/libs/llvm22/lib/Target/LoongArch
    contrib/libs/llvm22/lib/Target/LoongArch/AsmParser
    contrib/libs/llvm22/lib/Target/LoongArch/MCTargetDesc
    contrib/libs/llvm22/lib/Target/LoongArch/TargetInfo
    contrib/libs/llvm22/lib/Target/NVPTX
    contrib/libs/llvm22/lib/Target/NVPTX/MCTargetDesc
    contrib/libs/llvm22/lib/Target/NVPTX/TargetInfo
    contrib/libs/llvm22/lib/Target/PowerPC
    contrib/libs/llvm22/lib/Target/PowerPC/AsmParser
    contrib/libs/llvm22/lib/Target/PowerPC/MCTargetDesc
    contrib/libs/llvm22/lib/Target/PowerPC/TargetInfo
    contrib/libs/llvm22/lib/Target/WebAssembly
    contrib/libs/llvm22/lib/Target/WebAssembly/AsmParser
    contrib/libs/llvm22/lib/Target/WebAssembly/MCTargetDesc
    contrib/libs/llvm22/lib/Target/WebAssembly/TargetInfo
    contrib/libs/llvm22/lib/Target/WebAssembly/Utils
    contrib/libs/llvm22/lib/Target/X86
    contrib/libs/llvm22/lib/Target/X86/AsmParser
    contrib/libs/llvm22/lib/Target/X86/MCTargetDesc
    contrib/libs/llvm22/lib/Target/X86/TargetInfo
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
    contrib/libs/llvm22/lib/Transforms/AggressiveInstCombine
    contrib/libs/llvm22/lib/Transforms/CFGuard
    contrib/libs/llvm22/lib/Transforms/Coroutines
    contrib/libs/llvm22/lib/Transforms/HipStdPar
    contrib/libs/llvm22/lib/Transforms/IPO
    contrib/libs/llvm22/lib/Transforms/InstCombine
    contrib/libs/llvm22/lib/Transforms/Instrumentation
    contrib/libs/llvm22/lib/Transforms/ObjCARC
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
    contrib/libs/llvm22/lib/Transforms/Vectorize
)

ADDINCL(
    contrib/libs/llvm22/tools/bugpoint
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    BugDriver.cpp
    CrashDebugger.cpp
    ExecutionDriver.cpp
    ExtractFunction.cpp
    FindBugs.cpp
    Miscompilation.cpp
    OptimizerDriver.cpp
    ToolRunner.cpp
    bugpoint.cpp
)

END()
