# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TableGen
)

ADDINCL(
    contrib/libs/llvm22/utils/TableGen/Basic
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    ARMTargetDefEmitter.cpp
    Attributes.cpp
    CodeGenIntrinsics.cpp
    DirectiveEmitter.cpp
    IntrinsicEmitter.cpp
    RISCVTargetDefEmitter.cpp
    RuntimeLibcalls.cpp
    RuntimeLibcallsEmitter.cpp
    SDNodeProperties.cpp
    TableGen.cpp
    TargetFeaturesEmitter.cpp
    TargetLibraryInfoEmitter.cpp
    VTEmitter.cpp
)

END()
