# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/Frontend/HLSL
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CBuffer.cpp
    HLSLBinding.cpp
    HLSLResource.cpp
    HLSLRootSignature.cpp
    RootSignatureMetadata.cpp
    RootSignatureValidations.cpp
)

END()
