# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/Frontend/OpenMP
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRReader
    contrib/libs/llvm22/lib/Linker
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/ProfileData
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/AggressiveInstCombine
    contrib/libs/llvm22/lib/Transforms/InstCombine
    contrib/libs/llvm22/lib/Transforms/Instrumentation
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
    contrib/libs/llvm22/lib/Transforms/Vectorize
)

ADDINCL(
    contrib/libs/llvm22/lib/Transforms/IPO
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AlwaysInliner.cpp
    Annotation2Metadata.cpp
    ArgumentPromotion.cpp
    Attributor.cpp
    AttributorAttributes.cpp
    BarrierNoopPass.cpp
    BlockExtractor.cpp
    CalledValuePropagation.cpp
    ConstantMerge.cpp
    CrossDSOCFI.cpp
    DeadArgumentElimination.cpp
    ElimAvailExtern.cpp
    EmbedBitcodePass.cpp
    ExpandVariadics.cpp
    ExtractGV.cpp
    FatLTOCleanup.cpp
    ForceFunctionAttrs.cpp
    FunctionAttrs.cpp
    FunctionImport.cpp
    FunctionSpecialization.cpp
    GlobalDCE.cpp
    GlobalOpt.cpp
    GlobalSplit.cpp
    HotColdSplitting.cpp
    IPO.cpp
    IROutliner.cpp
    InferFunctionAttrs.cpp
    Inliner.cpp
    Internalize.cpp
    LoopExtractor.cpp
    LowerTypeTests.cpp
    MemProfContextDisambiguation.cpp
    MergeFunctions.cpp
    ModuleInliner.cpp
    OpenMPOpt.cpp
    PartialInlining.cpp
    SCCP.cpp
    SampleContextTracker.cpp
    SampleProfile.cpp
    SampleProfileMatcher.cpp
    SampleProfileProbe.cpp
    StripDeadPrototypes.cpp
    StripSymbols.cpp
    ThinLTOBitcodeWriter.cpp
    WholeProgramDevirt.cpp
)

END()
