# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Option
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/lib/ToolDrivers/llvm-dlltool
    contrib/libs/llvm22/lib/ToolDrivers/llvm-dlltool
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DlltoolDriver.cpp
)

END()
