# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/CGData
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CodeGenData.cpp
    CodeGenDataReader.cpp
    CodeGenDataWriter.cpp
    OutlinedHashTree.cpp
    OutlinedHashTreeRecord.cpp
    StableFunctionMap.cpp
    StableFunctionMapRecord.cpp
)

END()
