# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/DebugInfo/GSYM
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CallSiteInfo.cpp
    DwarfTransformer.cpp
    ExtractRanges.cpp
    FileWriter.cpp
    FunctionInfo.cpp
    GsymContext.cpp
    GsymCreator.cpp
    GsymReader.cpp
    Header.cpp
    InlineInfo.cpp
    LineTable.cpp
    LookupResult.cpp
    MergedFunctionsInfo.cpp
    ObjectFileTransformer.cpp
)

END()
