# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/ProfileData
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/Transforms/Instrumentation
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AddressSanitizer.cpp
    AllocToken.cpp
    BlockCoverageInference.cpp
    BoundsChecking.cpp
    CGProfile.cpp
    ControlHeightReduction.cpp
    DataFlowSanitizer.cpp
    GCOVProfiling.cpp
    HWAddressSanitizer.cpp
    IndirectCallPromotion.cpp
    InstrProfiling.cpp
    KCFI.cpp
    LowerAllowCheckPass.cpp
    MemProfInstrumentation.cpp
    MemProfUse.cpp
    MemorySanitizer.cpp
    NumericalStabilitySanitizer.cpp
    PGOCtxProfFlattening.cpp
    PGOCtxProfLowering.cpp
    PGOForceFunctionAttrs.cpp
    PGOInstrumentation.cpp
    PGOMemOPSizeOpt.cpp
    RealtimeSanitizer.cpp
    SanitizerBinaryMetadata.cpp
    SanitizerCoverage.cpp
    ThreadSanitizer.cpp
    TypeSanitizer.cpp
    ValueProfileCollector.cpp
)

END()
