# Generated by devtools/yamaker.

PROGRAM()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/AsmParser
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitstream/Reader
    contrib/libs/llvm22/lib/DebugInfo/CodeView
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRReader
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Option
    contrib/libs/llvm22/lib/Remarks
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/tools/llvm-readobj
    contrib/libs/llvm22/tools/llvm-readobj
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    ARMWinEHPrinter.cpp
    COFFDumper.cpp
    COFFImportDumper.cpp
    ELFDumper.cpp
    MachODumper.cpp
    ObjDumper.cpp
    WasmDumper.cpp
    Win64EHDumper.cpp
    WindowsResourceDumper.cpp
    XCOFFDumper.cpp
    llvm-readobj-driver.cpp
    llvm-readobj.cpp
)

END()
