# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/DebugInfo/DWARF
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DWARFAbbreviationDeclaration.cpp
    DWARFAcceleratorTable.cpp
    DWARFAddressRange.cpp
    DWARFCFIPrinter.cpp
    DWARFCompileUnit.cpp
    DWARFContext.cpp
    DWARFDebugAbbrev.cpp
    DWARFDebugAddr.cpp
    DWARFDebugArangeSet.cpp
    DWARFDebugAranges.cpp
    DWARFDebugFrame.cpp
    DWARFDebugInfoEntry.cpp
    DWARFDebugLine.cpp
    DWARFDebugLoc.cpp
    DWARFDebugMacro.cpp
    DWARFDebugPubTable.cpp
    DWARFDebugRangeList.cpp
    DWARFDebugRnglists.cpp
    DWARFDie.cpp
    DWARFExpressionPrinter.cpp
    DWARFFormValue.cpp
    DWARFGdbIndex.cpp
    DWARFListTable.cpp
    DWARFLocationExpression.cpp
    DWARFTypeUnit.cpp
    DWARFUnit.cpp
    DWARFUnitIndex.cpp
    DWARFUnwindTablePrinter.cpp
    DWARFVerifier.cpp
)

END()
