# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/DebugInfo/CodeView
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/ProfileData
    contrib/libs/llvm22/lib/Remarks
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/TargetParser
)

IF (SANITIZER_TYPE == "undefined")
    PEERDIR(
        contrib/libs/llvm22/lib/Target/ARM/MCTargetDesc
    )
ENDIF()

ADDINCL(
    contrib/libs/llvm22/lib/CodeGen/AsmPrinter
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AIXException.cpp
    ARMException.cpp
    AccelTable.cpp
    AddressPool.cpp
    AsmPrinter.cpp
    AsmPrinterDwarf.cpp
    AsmPrinterInlineAsm.cpp
    CodeViewDebug.cpp
    DIE.cpp
    DIEHash.cpp
    DbgEntityHistoryCalculator.cpp
    DebugHandlerBase.cpp
    DebugLocStream.cpp
    DwarfCFIException.cpp
    DwarfCompileUnit.cpp
    DwarfDebug.cpp
    DwarfExpression.cpp
    DwarfFile.cpp
    DwarfStringPool.cpp
    DwarfUnit.cpp
    EHStreamer.cpp
    ErlangGCPrinter.cpp
    OcamlGCPrinter.cpp
    PseudoProbePrinter.cpp
    WasmException.cpp
    WinCFGuard.cpp
    WinException.cpp
)

END()
