# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGen/AsmPrinter
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/DWARFLinker
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/DWARFLinker/Classic
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DWARFLinker.cpp
    DWARFLinkerCompileUnit.cpp
    DWARFLinkerDeclContext.cpp
    DWARFStreamer.cpp
)

END()
