/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_perforator_unwind_Native */

#ifndef _Included_tech_perforator_unwind_Native
#define _Included_tech_perforator_unwind_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_perforator_unwind_Native
 * Method:    unwind0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_perforator_unwind_Native_unwind0
  (JNIEnv *, jclass);

/*
 * Class:     tech_perforator_unwind_Native
 * Method:    unwindIfZero0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tech_perforator_unwind_Native_unwindIfZero0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
