# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/AsmParser
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
)

ADDINCL(
    contrib/libs/llvm22/lib/CodeGen/MIRParser
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    MILexer.cpp
    MIParser.cpp
    MIRParser.cpp
)

END()
