package uprobe

import (
	"sync"
)

type SymbolInfo struct {
	Name        string
	LocalOffset uint64
}

type BinaryInfo struct {
	BuildID string
	// Offset into the binary where the uprobe is located
	Offset uint64
}

type OutputInfo struct {
	ProfileName string
	SampleKind  string
}

type UprobeInfo struct {
	SymbolInfo
	BinaryInfo
	OutputInfo
}

// Resolver is a simple map which allows to resolve the specific
// uprobe by its key - an offset in the binary.
// This provides a way to map samples from profiler to the specific uprobe
// even if they are generated by a single uprobe bpf program.
// Resolver may be replaced with a use of bpf cookie which allows passing
// uprobe_id to each bpf link.
type Resolver struct {
	sync.RWMutex
	uprobes map[BinaryInfo]*UprobeInfo
}

func NewResolver() *Resolver {
	return &Resolver{
		uprobes: make(map[BinaryInfo]*UprobeInfo),
	}
}

func (r *Resolver) Add(uprobeInfo *UprobeInfo) {
	r.Lock()
	defer r.Unlock()
	r.uprobes[uprobeInfo.BinaryInfo] = uprobeInfo
}

func (r *Resolver) Remove(key BinaryInfo) {
	r.Lock()
	defer r.Unlock()
	delete(r.uprobes, key)
}

func (r *Resolver) Resolve(key BinaryInfo) *UprobeInfo {
	r.RLock()
	defer r.RUnlock()
	return r.uprobes[key]
}
