# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGen/GlobalISel
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRPrinter
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/Transforms/AggressiveInstCombine
    contrib/libs/llvm22/lib/Transforms/CFGuard
    contrib/libs/llvm22/lib/Transforms/Coroutines
    contrib/libs/llvm22/lib/Transforms/HipStdPar
    contrib/libs/llvm22/lib/Transforms/IPO
    contrib/libs/llvm22/lib/Transforms/InstCombine
    contrib/libs/llvm22/lib/Transforms/Instrumentation
    contrib/libs/llvm22/lib/Transforms/ObjCARC
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
    contrib/libs/llvm22/lib/Transforms/Vectorize
)

ADDINCL(
    contrib/libs/llvm22/lib/Passes
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CodeGenPassBuilder.cpp
    OptimizationLevel.cpp
    PassBuilder.cpp
    PassBuilderBindings.cpp
    PassBuilderPipelines.cpp
    StandardInstrumentations.cpp
)

END()
