# Generated by devtools/yamaker.

LIBRARY()

LICENSE(
    Apache-2.0 WITH LLVM-exception AND
    NCSA
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/TargetParser
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AArch64TargetParser.cpp
    ARMTargetParser.cpp
    ARMTargetParserCommon.cpp
    CSKYTargetParser.cpp
    Host.cpp
    LoongArchTargetParser.cpp
    PPCTargetParser.cpp
    RISCVISAInfo.cpp
    RISCVTargetParser.cpp
    SubtargetFeature.cpp
    TargetDataLayout.cpp
    TargetParser.cpp
    Triple.cpp
    X86TargetParser.cpp
    XtensaTargetParser.cpp
)

END()
