# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/TextAPI
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Architecture.cpp
    ArchitectureSet.cpp
    InterfaceFile.cpp
    PackedVersion.cpp
    Platform.cpp
    RecordVisitor.cpp
    RecordsSlice.cpp
    Symbol.cpp
    SymbolSet.cpp
    Target.cpp
    TextAPIError.cpp
    TextStub.cpp
    TextStubCommon.cpp
    TextStubV5.cpp
    Utils.cpp
)

END()
