# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGen/GlobalISel
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/ExecutionEngine
    contrib/libs/llvm22/lib/ExecutionEngine/Orc
    contrib/libs/llvm22/lib/ExecutionEngine/RuntimeDyld
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCDisassembler
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/MCA
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/ObjectYAML
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/tools/llvm-exegesis/lib
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    Analysis.cpp
    Assembler.cpp
    BenchmarkResult.cpp
    BenchmarkRunner.cpp
    Clustering.cpp
    CodeTemplate.cpp
    DisassemblerHelper.cpp
    Error.cpp
    LatencyBenchmarkRunner.cpp
    LlvmState.cpp
    MCInstrDescView.cpp
    ParallelSnippetGenerator.cpp
    PerfHelper.cpp
    RegisterAliasing.cpp
    RegisterValue.cpp
    ResultAggregator.cpp
    SchedClassResolution.cpp
    SerialSnippetGenerator.cpp
    SnippetFile.cpp
    SnippetGenerator.cpp
    SnippetRepetitor.cpp
    SubprocessMemory.cpp
    Target.cpp
    UopsBenchmarkRunner.cpp
    ValidationEvent.cpp
)

END()
