# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/Transforms/InstCombine
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    InstCombineAddSub.cpp
    InstCombineAndOrXor.cpp
    InstCombineAtomicRMW.cpp
    InstCombineCalls.cpp
    InstCombineCasts.cpp
    InstCombineCompares.cpp
    InstCombineLoadStoreAlloca.cpp
    InstCombineMulDivRem.cpp
    InstCombineNegator.cpp
    InstCombinePHI.cpp
    InstCombineSelect.cpp
    InstCombineShifts.cpp
    InstCombineSimplifyDemanded.cpp
    InstCombineVectorOps.cpp
    InstructionCombining.cpp
)

END()
