server:
  insecure: true
storage:
  databases:
    clickhouse:
      replicas: {{ include "perforator.clickhouse.endpoints" . | nindent 8 }}
      db: {{ .Values.databases.clickhouse.db }}
      user: {{ .Values.databases.clickhouse.user }}
      password_env: "CLICKHOUSE_PASSWORD"
      tls:
        enabled: {{ .Values.databases.clickhouse.tls.enabled }}
        ca_file_path: {{ include "perforator.clickhouse.tlsCACert" . }}
        insecure_skip_verify: {{ .Values.databases.clickhouse.tls.insecureSkipVerify }}
      insecure: {{ .Values.databases.clickhouse.insecure }}
      ca_cert_path: {{ .Values.databases.clickhouse.ca_cert_path }}
    postgres:
      auth:
        user: {{ .Values.databases.postgresql.user }}
        password_env: "POSTGRES_PASSWORD"
      db: {{ .Values.databases.postgresql.db }}
      endpoints: {{ include "perforator.postgresql.endpoints" . | nindent 8 }}
      sslmode: {{ .Values.databases.postgresql.sslmode }}
      sslrootcert: {{ .Values.databases.postgresql.sslrootcert }}
    s3:
      endpoint: {{ include "perforator.s3.endpoint" . }}
      secret_key_path: "/etc/perforator/s3/secret_key.txt"
      access_key_path: "/etc/perforator/s3/access_key.txt"
      tls:
        enabled: {{ .Values.databases.s3.tls.enabled }}
        ca_file_path: {{ include "perforator.s3.tlsCACert" . }}
        insecure_skip_verify: {{ .Values.databases.s3.tls.insecureSkipVerify }}
      insecure: {{ .Values.databases.s3.insecure }}
      force_path_style: {{ .Values.databases.s3.force_path_style }}
      ca_cert_path: {{ .Values.databases.s3.ca_cert_path }}
  binaries:
    meta: "postgres"
    bucket: {{ .Values.databases.s3.buckets.binaries }}
binary_provider:
  file_cache:
  {{- with .Values.binproc.binary_provider.file_cache }}
    max_size: {{ .max_size }}
    max_items: {{ .max_items }}
    root_path: {{ .root_path }}
  {{- end }}
  max_simultaneous_downloads: {{ .Values.binproc.binary_provider.max_simultaneous_downloads }}
