# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/CGData
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/Extensions
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Linker
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Passes
    contrib/libs/llvm22/lib/Plugins
    contrib/libs/llvm22/lib/Remarks
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/AggressiveInstCombine
    contrib/libs/llvm22/lib/Transforms/IPO
    contrib/libs/llvm22/lib/Transforms/InstCombine
    contrib/libs/llvm22/lib/Transforms/Instrumentation
    contrib/libs/llvm22/lib/Transforms/ObjCARC
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/LTO
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    LTO.cpp
    LTOBackend.cpp
    LTOCodeGenerator.cpp
    LTOModule.cpp
    ThinLTOCodeGenerator.cpp
    UpdateCompilerUsed.cpp
)

END()
