# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Bitstream/Reader
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/Remarks
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    BitstreamRemarkParser.cpp
    BitstreamRemarkSerializer.cpp
    Remark.cpp
    RemarkFormat.cpp
    RemarkLinker.cpp
    RemarkParser.cpp
    RemarkSerializer.cpp
    RemarkStreamer.cpp
    RemarkStringTable.cpp
    YAMLRemarkParser.cpp
    YAMLRemarkSerializer.cpp
)

END()
