# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRReader
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
)

ADDINCL(
    contrib/libs/llvm22/lib/Object
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Archive.cpp
    ArchiveWriter.cpp
    Binary.cpp
    BuildID.cpp
    COFFImportFile.cpp
    COFFModuleDefinition.cpp
    COFFObjectFile.cpp
    DXContainer.cpp
    Decompressor.cpp
    ELF.cpp
    ELFObjectFile.cpp
    Error.cpp
    FaultMapParser.cpp
    GOFFObjectFile.cpp
    IRObjectFile.cpp
    IRSymtab.cpp
    MachOObjectFile.cpp
    MachOUniversal.cpp
    MachOUniversalWriter.cpp
    Minidump.cpp
    ModuleSymbolTable.cpp
    Object.cpp
    ObjectFile.cpp
    OffloadBinary.cpp
    OffloadBundle.cpp
    RecordStreamer.cpp
    RelocationResolver.cpp
    SFrameParser.cpp
    SymbolSize.cpp
    SymbolicFile.cpp
    TapiFile.cpp
    TapiUniversal.cpp
    WasmObjectFile.cpp
    WindowsMachineFlag.cpp
    WindowsResource.cpp
    XCOFFObjectFile.cpp
)

END()
