# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/TableGen
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DetailedRecordsBackend.cpp
    Error.cpp
    JSONBackend.cpp
    Main.cpp
    Parser.cpp
    Record.cpp
    SetTheory.cpp
    StringMatcher.cpp
    StringToOffsetTable.cpp
    TGLexer.cpp
    TGParser.cpp
    TGTimer.cpp
    TableGenBackend.cpp
    TableGenBackendSkeleton.cpp
)

END()
