# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/ObjCopy
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Archive.cpp
    COFF/COFFObjcopy.cpp
    COFF/COFFObject.cpp
    COFF/COFFReader.cpp
    COFF/COFFWriter.cpp
    CommonConfig.cpp
    ConfigManager.cpp
    DXContainer/DXContainerObjcopy.cpp
    DXContainer/DXContainerObject.cpp
    DXContainer/DXContainerReader.cpp
    DXContainer/DXContainerWriter.cpp
    ELF/ELFObjcopy.cpp
    ELF/ELFObject.cpp
    MachO/MachOLayoutBuilder.cpp
    MachO/MachOObjcopy.cpp
    MachO/MachOObject.cpp
    MachO/MachOReader.cpp
    MachO/MachOWriter.cpp
    ObjCopy.cpp
    XCOFF/XCOFFObjcopy.cpp
    XCOFF/XCOFFReader.cpp
    XCOFF/XCOFFWriter.cpp
    wasm/WasmObjcopy.cpp
    wasm/WasmObject.cpp
    wasm/WasmReader.cpp
    wasm/WasmWriter.cpp
)

END()
