# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/IPO
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/Transforms/Coroutines
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CoroAnnotationElide.cpp
    CoroCleanup.cpp
    CoroConditionalWrapper.cpp
    CoroEarly.cpp
    CoroElide.cpp
    CoroFrame.cpp
    CoroSplit.cpp
    Coroutines.cpp
    MaterializationUtils.cpp
    SpillUtils.cpp
    SuspendCrossingInfo.cpp
)

END()
