# Generated by devtools/yamaker.

PROGRAM(llvm-tblgen)

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TableGen
    library/cpp/sanitizer/include
)

ADDINCL(
    contrib/libs/llvm22/utils/TableGen
    contrib/libs/llvm22/utils/TableGen/Basic
    contrib/libs/llvm22/utils/TableGen/Common
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    AsmMatcherEmitter.cpp
    AsmWriterEmitter.cpp
    Basic/ARMTargetDefEmitter.cpp
    Basic/Attributes.cpp
    Basic/CodeGenIntrinsics.cpp
    Basic/DirectiveEmitter.cpp
    Basic/IntrinsicEmitter.cpp
    Basic/RISCVTargetDefEmitter.cpp
    Basic/RuntimeLibcalls.cpp
    Basic/RuntimeLibcallsEmitter.cpp
    Basic/SDNodeProperties.cpp
    Basic/TableGen.cpp
    Basic/TargetFeaturesEmitter.cpp
    Basic/TargetLibraryInfoEmitter.cpp
    Basic/VTEmitter.cpp
    CTagsEmitter.cpp
    CallingConvEmitter.cpp
    CodeEmitterGen.cpp
    CodeGenMapTable.cpp
    Common/AsmWriterInst.cpp
    Common/CodeGenDAGPatterns.cpp
    Common/CodeGenHwModes.cpp
    Common/CodeGenInstAlias.cpp
    Common/CodeGenInstruction.cpp
    Common/CodeGenRegisters.cpp
    Common/CodeGenSchedule.cpp
    Common/CodeGenTarget.cpp
    Common/GlobalISel/CXXPredicates.cpp
    Common/GlobalISel/CodeExpander.cpp
    Common/GlobalISel/CombinerUtils.cpp
    Common/GlobalISel/GlobalISelMatchTable.cpp
    Common/GlobalISel/GlobalISelMatchTableExecutorEmitter.cpp
    Common/GlobalISel/PatternParser.cpp
    Common/GlobalISel/Patterns.cpp
    Common/InfoByHwMode.cpp
    Common/InstructionEncoding.cpp
    Common/OptEmitter.cpp
    Common/PredicateExpander.cpp
    Common/SubtargetFeatureInfo.cpp
    Common/Types.cpp
    Common/Utils.cpp
    Common/VarLenCodeEmitterGen.cpp
    CompressInstEmitter.cpp
    DAGISelEmitter.cpp
    DAGISelMatcher.cpp
    DAGISelMatcherEmitter.cpp
    DAGISelMatcherGen.cpp
    DAGISelMatcherOpt.cpp
    DFAEmitter.cpp
    DFAPacketizerEmitter.cpp
    DXILEmitter.cpp
    DecoderEmitter.cpp
    DecoderTableEmitter.cpp
    DecoderTree.cpp
    DisassemblerEmitter.cpp
    ExegesisEmitter.cpp
    FastISelEmitter.cpp
    GlobalISelCombinerEmitter.cpp
    GlobalISelEmitter.cpp
    InstrDocsEmitter.cpp
    InstrInfoEmitter.cpp
    MacroFusionPredicatorEmitter.cpp
    OptionParserEmitter.cpp
    OptionRSTEmitter.cpp
    PseudoLoweringEmitter.cpp
    RegisterBankEmitter.cpp
    RegisterInfoEmitter.cpp
    SDNodeInfoEmitter.cpp
    SearchableTableEmitter.cpp
    SubtargetEmitter.cpp
    WebAssemblyDisassemblerEmitter.cpp
    X86DisassemblerTables.cpp
    X86FoldTablesEmitter.cpp
    X86InstrMappingEmitter.cpp
    X86MnemonicTables.cpp
    X86ModRMFilters.cpp
    X86RecognizableInstr.cpp
    llvm-tblgen.cpp
)

END()
