# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(GPL-2.0-only WITH Classpath-exception-2.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(25+4)

ORIGINAL_SOURCE(https://github.com/openjdk/jdk/archive/jdk-25+4.tar.gz)

NO_BUILD_IF(OS_ANDROID)

ADDINCL(
    GLOBAL contrib/libs/jdk/include
)

END()
