RECURSE(
    agent_gateway
    asyncfilecache
    asynctask
    binaryprocessor
    buildinfo
    custom_profiling_operation
    linguist
    logfield
    offline_processing
    servicediscovery
    symbolizer
    unwinder
    web
    xmetrics
)
