# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/SandboxIR
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    Argument.cpp
    BasicBlock.cpp
    Constant.cpp
    Context.cpp
    Function.cpp
    Instruction.cpp
    Module.cpp
    Pass.cpp
    PassManager.cpp
    Region.cpp
    Tracker.cpp
    Type.cpp
    Use.cpp
    User.cpp
    Value.cpp
)

END()
