# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target/AArch64
    contrib/libs/llvm22/lib/Target/AArch64/AsmParser
    contrib/libs/llvm22/lib/Target/AArch64/Disassembler
    contrib/libs/llvm22/lib/Target/AArch64/MCTargetDesc
    contrib/libs/llvm22/lib/Target/AArch64/TargetInfo
    contrib/libs/llvm22/lib/Target/AArch64/Utils
    contrib/libs/llvm22/tools/llvm-exegesis/lib
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/lib/Target/AArch64
    contrib/libs/llvm22/lib/Target/AArch64
    contrib/libs/llvm22/tools/llvm-exegesis/lib/AArch64
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    Target.cpp
)

END()
