# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/DebugInfo/CodeView
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/ObjectYAML
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    ArchiveEmitter.cpp
    ArchiveYAML.cpp
    COFFEmitter.cpp
    COFFYAML.cpp
    CodeViewYAMLDebugSections.cpp
    CodeViewYAMLSymbols.cpp
    CodeViewYAMLTypeHashing.cpp
    CodeViewYAMLTypes.cpp
    DWARFEmitter.cpp
    DWARFYAML.cpp
    DXContainerEmitter.cpp
    DXContainerYAML.cpp
    ELFEmitter.cpp
    ELFYAML.cpp
    GOFFEmitter.cpp
    GOFFYAML.cpp
    MachOEmitter.cpp
    MachOYAML.cpp
    MinidumpEmitter.cpp
    MinidumpYAML.cpp
    ObjectYAML.cpp
    OffloadEmitter.cpp
    OffloadYAML.cpp
    WasmEmitter.cpp
    WasmYAML.cpp
    XCOFFEmitter.cpp
    XCOFFYAML.cpp
    YAML.cpp
    yaml2obj.cpp
)

END()
