# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/lib/MC/MCParser
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AsmLexer.cpp
    AsmParser.cpp
    COFFAsmParser.cpp
    COFFMasmParser.cpp
    DarwinAsmParser.cpp
    ELFAsmParser.cpp
    GOFFAsmParser.cpp
    MCAsmParser.cpp
    MCAsmParserExtension.cpp
    MCTargetAsmParser.cpp
    MasmParser.cpp
    WasmAsmParser.cpp
    XCOFFAsmParser.cpp
)

END()
