{{- if .Values.binproc.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perforator.fullname" . }}-binproc-config
  namespace: {{ .Release.Namespace }}
data:  
{{- if .Values.binproc.config.useCustom }}  
  config.yaml: |- {{- tpl .Values.binproc.config.custom . | nindent 4 }}
{{- else }}
  config.yaml: |- {{- tpl (.Files.Get "config/binproc.yaml") . | nindent 4 }}
{{- end }}
{{- end }}
