# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/CodeGen/SelectionDAG
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DAGCombiner.cpp
    FastISel.cpp
    FunctionLoweringInfo.cpp
    InstrEmitter.cpp
    LegalizeDAG.cpp
    LegalizeFloatTypes.cpp
    LegalizeIntegerTypes.cpp
    LegalizeTypes.cpp
    LegalizeTypesGeneric.cpp
    LegalizeVectorOps.cpp
    LegalizeVectorTypes.cpp
    ResourcePriorityQueue.cpp
    SDNodeInfo.cpp
    ScheduleDAGFast.cpp
    ScheduleDAGRRList.cpp
    ScheduleDAGSDNodes.cpp
    ScheduleDAGVLIW.cpp
    SelectionDAG.cpp
    SelectionDAGAddressAnalysis.cpp
    SelectionDAGBuilder.cpp
    SelectionDAGDumper.cpp
    SelectionDAGISel.cpp
    SelectionDAGPrinter.cpp
    SelectionDAGTargetInfo.cpp
    StatepointLowering.cpp
    TargetLowering.cpp
)

END()
