# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
)

ADDINCL(
    contrib/libs/llvm22/lib/TextAPI/BinaryReader
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DylibReader.cpp
)

END()
