# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target/X86
    contrib/libs/llvm22/lib/Target/X86/AsmParser
    contrib/libs/llvm22/lib/Target/X86/Disassembler
    contrib/libs/llvm22/lib/Target/X86/MCTargetDesc
    contrib/libs/llvm22/lib/Target/X86/TargetInfo
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/tools/llvm-exegesis/lib
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/lib/Target/X86
    contrib/libs/llvm22/lib/Target/X86
    contrib/libs/llvm22/tools/llvm-exegesis/lib/X86
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    Target.cpp
    X86Counter.cpp
)

END()
