# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TableGen
    contrib/libs/llvm22/utils/TableGen/Basic
)

ADDINCL(
    contrib/libs/llvm22/utils/TableGen
    contrib/libs/llvm22/utils/TableGen/Common
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    AsmWriterInst.cpp
    CodeGenDAGPatterns.cpp
    CodeGenHwModes.cpp
    CodeGenInstAlias.cpp
    CodeGenInstruction.cpp
    CodeGenRegisters.cpp
    CodeGenSchedule.cpp
    CodeGenTarget.cpp
    GlobalISel/CXXPredicates.cpp
    GlobalISel/CodeExpander.cpp
    GlobalISel/CombinerUtils.cpp
    GlobalISel/GlobalISelMatchTable.cpp
    GlobalISel/GlobalISelMatchTableExecutorEmitter.cpp
    GlobalISel/PatternParser.cpp
    GlobalISel/Patterns.cpp
    InfoByHwMode.cpp
    InstructionEncoding.cpp
    OptEmitter.cpp
    PredicateExpander.cpp
    SubtargetFeatureInfo.cpp
    Types.cpp
    Utils.cpp
    VarLenCodeEmitterGen.cpp
)

END()
