# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/LTO
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCDisassembler
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/Target/AArch64
    contrib/libs/llvm22/lib/Target/AArch64/AsmParser
    contrib/libs/llvm22/lib/Target/AArch64/Disassembler
    contrib/libs/llvm22/lib/Target/AArch64/MCTargetDesc
    contrib/libs/llvm22/lib/Target/AArch64/TargetInfo
    contrib/libs/llvm22/lib/Target/ARM
    contrib/libs/llvm22/lib/Target/ARM/AsmParser
    contrib/libs/llvm22/lib/Target/ARM/Disassembler
    contrib/libs/llvm22/lib/Target/ARM/MCTargetDesc
    contrib/libs/llvm22/lib/Target/ARM/TargetInfo
    contrib/libs/llvm22/lib/Target/BPF
    contrib/libs/llvm22/lib/Target/BPF/AsmParser
    contrib/libs/llvm22/lib/Target/BPF/Disassembler
    contrib/libs/llvm22/lib/Target/BPF/MCTargetDesc
    contrib/libs/llvm22/lib/Target/BPF/TargetInfo
    contrib/libs/llvm22/lib/Target/LoongArch
    contrib/libs/llvm22/lib/Target/LoongArch/AsmParser
    contrib/libs/llvm22/lib/Target/LoongArch/Disassembler
    contrib/libs/llvm22/lib/Target/LoongArch/MCTargetDesc
    contrib/libs/llvm22/lib/Target/LoongArch/TargetInfo
    contrib/libs/llvm22/lib/Target/NVPTX
    contrib/libs/llvm22/lib/Target/NVPTX/MCTargetDesc
    contrib/libs/llvm22/lib/Target/NVPTX/TargetInfo
    contrib/libs/llvm22/lib/Target/PowerPC
    contrib/libs/llvm22/lib/Target/PowerPC/AsmParser
    contrib/libs/llvm22/lib/Target/PowerPC/Disassembler
    contrib/libs/llvm22/lib/Target/PowerPC/MCTargetDesc
    contrib/libs/llvm22/lib/Target/PowerPC/TargetInfo
    contrib/libs/llvm22/lib/Target/WebAssembly
    contrib/libs/llvm22/lib/Target/WebAssembly/AsmParser
    contrib/libs/llvm22/lib/Target/WebAssembly/Disassembler
    contrib/libs/llvm22/lib/Target/WebAssembly/MCTargetDesc
    contrib/libs/llvm22/lib/Target/WebAssembly/TargetInfo
    contrib/libs/llvm22/lib/Target/X86
    contrib/libs/llvm22/lib/Target/X86/AsmParser
    contrib/libs/llvm22/lib/Target/X86/Disassembler
    contrib/libs/llvm22/lib/Target/X86/MCTargetDesc
    contrib/libs/llvm22/lib/Target/X86/TargetInfo
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/tools/lto
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    LTODisassembler.cpp
    lto.cpp
)

END()
