# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/ExecutionEngine/Orc/Shared
    contrib/libs/llvm22/lib/ExecutionEngine/Orc/TargetProcess
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Option
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/lib/ExecutionEngine/JITLink
    contrib/libs/llvm22/lib/ExecutionEngine/JITLink
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    COFF.cpp
    COFFDirectiveParser.cpp
    COFFLinkGraphBuilder.cpp
    COFF_x86_64.cpp
    CompactUnwindSupport.cpp
    DWARFRecordSectionSplitter.cpp
    EHFrameSupport.cpp
    ELF.cpp
    ELFLinkGraphBuilder.cpp
    ELF_aarch32.cpp
    ELF_aarch64.cpp
    ELF_loongarch.cpp
    ELF_ppc64.cpp
    ELF_riscv.cpp
    ELF_systemz.cpp
    ELF_x86.cpp
    ELF_x86_64.cpp
    JITLink.cpp
    JITLinkGeneric.cpp
    JITLinkMemoryManager.cpp
    MachO.cpp
    MachOLinkGraphBuilder.cpp
    MachO_arm64.cpp
    MachO_x86_64.cpp
    XCOFF.cpp
    XCOFFLinkGraphBuilder.cpp
    XCOFF_ppc64.cpp
    aarch32.cpp
    aarch64.cpp
    loongarch.cpp
    ppc64.cpp
    riscv.cpp
    systemz.cpp
    x86.cpp
    x86_64.cpp
)

END()
