# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
)

ADDINCL(
    contrib/libs/llvm22/lib/Demangle
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DLangDemangle.cpp
    Demangle.cpp
    ItaniumDemangle.cpp
    MicrosoftDemangle.cpp
    MicrosoftDemangleNodes.cpp
    RustDemangle.cpp
)

END()
