FROM ubuntu:24.04 AS build

RUN apt update \
 && apt install -y python3.12 python-is-python3

WORKDIR /perforator

COPY . /perforator

RUN --mount=type=cache,target=/root/.ya/build,sharing=locked --mount=type=cache,target=/root/.ya/tools,sharing=locked \
 ./ya make -r --output /out perforator/bundle

####################################################################################################################

FROM ubuntu:24.04 AS autofdo_build

RUN apt update && \
 apt install -y libunwind-dev libgflags-dev libssl-dev libelf-dev protobuf-compiler \
 cmake libzstd-dev clang g++ git build-essential

WORKDIR /autofdo

RUN git clone --recursive --revision 8f9ab68921f364a6433086245ca3f19befacfeb1 --depth 1 https://github.com/google/autofdo.git
RUN cd autofdo && git submodule update --init --recursive && \
 mkdir build && cd build && \
 cmake -DENABLE_TOOL=LLVM -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ../ && \
 make -j $(nproc) create_llvm_prof

####################################################################################################################

FROM ubuntu:24.04 AS base
RUN apt-get update && apt-get install -y ca-certificates

####################################################################################################################

FROM base AS agent
COPY --from=build /out/perforator/bundle/agent /perforator/agent

####################################################################################################################

FROM base AS gc
COPY --from=build /out/perforator/bundle/gc /perforator/gc

####################################################################################################################

FROM base AS storage
COPY --from=build /out/perforator/bundle/storage /perforator/storage

####################################################################################################################

FROM base AS proxy
COPY --from=build /out/perforator/bundle/proxy /perforator/proxy
COPY --from=autofdo_build /autofdo/autofdo/build/create_llvm_prof /perforator/create_llvm_prof

####################################################################################################################

FROM base AS web
COPY --from=build /out/perforator/bundle/web /perforator/web

####################################################################################################################

FROM base AS migrate
COPY --from=build /out/perforator/bundle/migrate /perforator/migrate

####################################################################################################################

FROM base AS offline_processing
COPY --from=build /out/perforator/bundle/offline_processing /perforator/offline_processing

####################################################################################################################

FROM base AS cli
COPY --from=build /out/perforator/bundle/cli /perforator/cli
