# Generated by devtools/yamaker.

PROGRAM()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/AsmParser
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitstream/Reader
    contrib/libs/llvm22/lib/DebugInfo/DWARF
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/IRReader
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/MC/MCDisassembler
    contrib/libs/llvm22/lib/MC/MCParser
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Remarks
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target/AArch64/MCTargetDesc
    contrib/libs/llvm22/lib/Target/AArch64/TargetInfo
    contrib/libs/llvm22/lib/Target/AArch64/Utils
    contrib/libs/llvm22/lib/Target/ARM/MCTargetDesc
    contrib/libs/llvm22/lib/Target/ARM/TargetInfo
    contrib/libs/llvm22/lib/Target/ARM/Utils
    contrib/libs/llvm22/lib/Target/BPF/MCTargetDesc
    contrib/libs/llvm22/lib/Target/BPF/TargetInfo
    contrib/libs/llvm22/lib/Target/LoongArch/MCTargetDesc
    contrib/libs/llvm22/lib/Target/LoongArch/TargetInfo
    contrib/libs/llvm22/lib/Target/NVPTX/MCTargetDesc
    contrib/libs/llvm22/lib/Target/NVPTX/TargetInfo
    contrib/libs/llvm22/lib/Target/PowerPC/MCTargetDesc
    contrib/libs/llvm22/lib/Target/PowerPC/TargetInfo
    contrib/libs/llvm22/lib/Target/WebAssembly/MCTargetDesc
    contrib/libs/llvm22/lib/Target/WebAssembly/TargetInfo
    contrib/libs/llvm22/lib/Target/X86/MCTargetDesc
    contrib/libs/llvm22/lib/Target/X86/TargetInfo
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
)

ADDINCL(
    contrib/libs/llvm22/tools/llvm-dwarfdump
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    SectionSizes.cpp
    Statistics.cpp
    llvm-dwarfdump.cpp
)

END()
