# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/DebugInfo/DWARF/LowLevel
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    contrib/libs/llvm22/lib/DWARFCFIChecker
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DWARFCFIAnalysis.cpp
    DWARFCFIFunctionFrameAnalyzer.cpp
    DWARFCFIFunctionFrameStreamer.cpp
    DWARFCFIState.cpp
)

END()
