# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/CodeGen
    contrib/libs/llvm22/lib/CodeGen/SelectionDAG
    contrib/libs/llvm22/lib/CodeGenTypes
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/CodeGen/GlobalISel
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    CSEInfo.cpp
    CSEMIRBuilder.cpp
    CallLowering.cpp
    Combiner.cpp
    CombinerHelper.cpp
    CombinerHelperArtifacts.cpp
    CombinerHelperCasts.cpp
    CombinerHelperCompares.cpp
    CombinerHelperVectorOps.cpp
    GIMatchTableExecutor.cpp
    GISelChangeObserver.cpp
    GISelValueTracking.cpp
    GlobalISel.cpp
    IRTranslator.cpp
    InlineAsmLowering.cpp
    InstructionSelect.cpp
    InstructionSelector.cpp
    LegacyLegalizerInfo.cpp
    LegalityPredicates.cpp
    LegalizeMutations.cpp
    Legalizer.cpp
    LegalizerHelper.cpp
    LegalizerInfo.cpp
    LoadStoreOpt.cpp
    Localizer.cpp
    LostDebugLocObserver.cpp
    MachineFloatingPointPredicateUtils.cpp
    MachineIRBuilder.cpp
    RegBankSelect.cpp
    Utils.cpp
)

END()
