# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/FuzzMutate
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCDIR(contrib/libs/llvm22/lib/FuzzMutate)

SRCS(
    IRMutator.cpp
    OpDescriptor.cpp
    Operations.cpp
    RandomIRBuilder.cpp
)

END()
