# Generated by devtools/yamaker.

PROGRAM()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
)

ADDINCL(
    contrib/libs/llvm22/tools/llvm-config
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DCMAKE_CFG_INTDIR=\"MinSizeRel\"
    -DLLVM_BUILD_STATIC
)

SRCS(
    llvm-config.cpp
)

END()
