# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/Frontend/Atomic
    contrib/libs/llvm22/lib/Frontend/Offloading
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/Transforms/Scalar
    contrib/libs/llvm22/lib/Transforms/Utils
)

ADDINCL(
    contrib/libs/llvm22/lib/Frontend/OpenMP
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DirectiveNameParser.cpp
    OMP.cpp
    OMPContext.cpp
    OMPIRBuilder.cpp
)

END()
