syntax = "proto3";

package NPerforator.NBinaryProcessing.NJvm;

import "perforator/agent/preprocessing/proto/jvm/meta.proto";

option go_package = "github.com/yandex/perforator/perforator/agent/preprocessing/proto/jvm";

message Cheatsheet {
    optional int64 code_blob_name = 3;
    optional int64 code_blob_frame_size = 4;
    optional int64 code_blob_kind = 5 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 22];
    optional int64 code_blob_kind_nmethod = 6 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 22];

    optional int64 code_heap_log2_segment_size = 7;
    optional int64 code_heap_memory = 8;
    optional int64 code_heap_segmap = 9;
    optional int64 code_heap_next_segment = 10;

    optional int64 heap_block_header_length = 11;
    optional int64 heap_block_header_used = 12;
    optional int64 heap_block_header = 13;
    optional int64 heap_block_allocated_space = 14;

    optional int64 constant_pool_pool_holder = 15;
    optional int64 constant_pool_base_offset = 16;

    optional int64 const_method_constants = 17;
    optional int64 const_method_name_index = 18;

    optional int64 method_const_method = 19;

    optional int64 nmethod_method = 20;
    optional int64 nmethod_immutable_data = 35 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 22];
    optional int64 nmethod_scopes_pcs = 36;
    optional int64 nmethod_scopes_data_offset = 37 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 22];
    optional int64 nmethod_scopes_data_addr = 48 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_lte) = 21];
    optional int64 nmethod_speculations = 38;
    optional int64 nmethod_mutable_data = 41 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 25];
    optional int64 nmethod_mutable_data_size = 43  [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 25];
    optional int64 nmethod_data_offset = 44 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_lte) = 24];
    optional int64 nmethod_metadata_offset = 45 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_lte) = 24];
    optional int64 nmethod_jvmci_data_offset = 46 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_lte) = 24];
    optional int64 nmethod_relocation_size = 42 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_gte) = 22];
    optional int64 nmethod_dependencies_offset = 47 [(NPerforator.NBinaryProcessing.NJvm.required_if_java_lte) = 21];

    optional int64 pc_desc_size = 34;
    optional int64 pc_desc_pc_offset = 39;
    optional int64 pc_desc_scope_decode_offset = 40;

    optional int64 growable_array_data = 21;
    optional int64 growable_array_length = 22;

    optional int64 klass_name = 23;
    
    optional int64 stub_queue_stub_buffer = 24;
    optional int64 stub_queue_buffer_limit = 25;

    optional int64 symbol_body = 26;
    optional int64 symbol_length = 27;

    optional int64 virtual_space_low = 28;
    optional int64 virtual_space_high = 29;

    optional uint64 code_cache_heaps = 30;
    optional uint64 abstract_interpreter_code = 31;

    optional int64 frame_return_addr_offset = 32;
    optional int64 frame_interpreter_frame_method_offset = 33;
}

message JvmAnalysis {
    Cheatsheet cheatsheet = 1;

    uint32 version = 4;
    string version_string = 5;

    enum Status {
        STATUS_NOT_JVM = 0;
        STATUS_OK = 1;
        STATUS_ERROR = 2;
    }

    Status status = 2;
    string error_message = 3;
}
