# Generated by devtools/yamaker.

PROGRAM()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/include
    contrib/libs/llvm22/lib/Demangle
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Option
    contrib/libs/llvm22/lib/Support
)

ADDINCL(
    ${ARCADIA_BUILD_ROOT}/contrib/libs/llvm22/tools/llvm-strings
    contrib/libs/llvm22/tools/llvm-strings
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    -DLLVM_BUILD_STATIC
)

SRCS(
    llvm-strings.cpp
)

END()
