# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(22.1.7)

PEERDIR(
    contrib/libs/llvm22
    contrib/libs/llvm22/lib/Analysis
    contrib/libs/llvm22/lib/BinaryFormat
    contrib/libs/llvm22/lib/Bitcode/Reader
    contrib/libs/llvm22/lib/Bitcode/Writer
    contrib/libs/llvm22/lib/ExecutionEngine
    contrib/libs/llvm22/lib/ExecutionEngine/JITLink
    contrib/libs/llvm22/lib/ExecutionEngine/Orc/Shared
    contrib/libs/llvm22/lib/ExecutionEngine/Orc/TargetProcess
    contrib/libs/llvm22/lib/ExecutionEngine/RuntimeDyld
    contrib/libs/llvm22/lib/IR
    contrib/libs/llvm22/lib/MC
    contrib/libs/llvm22/lib/Object
    contrib/libs/llvm22/lib/Passes
    contrib/libs/llvm22/lib/Support
    contrib/libs/llvm22/lib/Target
    contrib/libs/llvm22/lib/TargetParser
    contrib/libs/llvm22/lib/TextAPI
    contrib/libs/llvm22/lib/Transforms/Utils
    contrib/libs/llvm22/lib/WindowsDriver
)

ADDINCL(
    contrib/libs/llvm22/lib/ExecutionEngine/Orc
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    AbsoluteSymbols.cpp
    BacktraceTools.cpp
    COFF.cpp
    COFFPlatform.cpp
    COFFVCRuntimeSupport.cpp
    CompileOnDemandLayer.cpp
    CompileUtils.cpp
    Core.cpp
    DebugUtils.cpp
    EHFrameRegistrationPlugin.cpp
    ELFNixPlatform.cpp
    EPCDynamicLibrarySearchGenerator.cpp
    EPCGenericDylibManager.cpp
    EPCGenericJITLinkMemoryManager.cpp
    EPCGenericRTDyldMemoryManager.cpp
    EPCIndirectionUtils.cpp
    ExecutionUtils.cpp
    ExecutorProcessControl.cpp
    ExecutorResolutionGenerator.cpp
    IRCompileLayer.cpp
    IRPartitionLayer.cpp
    IRTransformLayer.cpp
    InProcessMemoryAccess.cpp
    IndirectionUtils.cpp
    JITLinkRedirectableSymbolManager.cpp
    JITLinkReentryTrampolines.cpp
    JITTargetMachineBuilder.cpp
    LLJIT.cpp
    Layer.cpp
    LazyObjectLinkingLayer.cpp
    LazyReexports.cpp
    LinkGraphLayer.cpp
    LinkGraphLinkingLayer.cpp
    LoadLinkableFile.cpp
    LookupAndRecordAddrs.cpp
    MachO.cpp
    MachOPlatform.cpp
    Mangling.cpp
    MapperJITLinkMemoryManager.cpp
    MemoryMapper.cpp
    ObjectFileInterface.cpp
    ObjectLinkingLayer.cpp
    ObjectTransformLayer.cpp
    OrcABISupport.cpp
    OrcV2CBindings.cpp
    RTDyldObjectLinkingLayer.cpp
    ReOptimizeLayer.cpp
    RedirectionManager.cpp
    SectCreate.cpp
    SelfExecutorProcessControl.cpp
    SimpleRemoteEPC.cpp
    SimpleRemoteMemoryMapper.cpp
    SpeculateAnalyses.cpp
    Speculation.cpp
    TaskDispatch.cpp
    ThreadSafeModule.cpp
    UnwindInfoRegistrationPlugin.cpp
)

END()
